# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

resources:
  repositories:
  - repository: self
    type: git
    ref: main

parameters:
  - name: branch
    type: string
    default: a11y
    

stages:
- stage: DeployEnv
  jobs:
  - deployment: DeployEnv
    displayName: Deploy code
    environment:
      name: magento_local
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            displayName: "Deploy script"
            inputs:
              script: |
                cd /home/vagrant/${{ parameters.branch }}/magento-base
                [[ "${{ parameters.branch }}" == "a11y"]] && git checkout UserStory-accessibility-epam
                if [[ "${{ parameters.branch }}" == "a11y"]]; then git checkout jp/dev; cd packages/magento2-jp; git checkout dev/magento-2.4.2-compatibility; fi
                git reset --hard
                git pull
                sudo ln -s /home/vagrant/${{ parameters.branch }}/magento-base /var/www/${{ parameters.branch }}
                sudo cp -r /home/vagrant/media/* /var/www/${{ parameters.branch }}/pub/media/
                sudo chown -R magento:www-data /var/www/${{ parameters.branch }}
                cd /var/www/${{ parameters.branch }}
                sudo chown -R magento:www-data .
                sudo su magento -c "composer install --no-interaction"
                sudo su magento -c "php bin/magento setup:install --base-url=http://${{ parameters.branch }}.172.30.1.10.nip.io/ --db-host=localhost:3306 --db-name=${{ parameters.branch }} --db-user=root --db-password=P@ssw0rd --admin-firstname=Magento --admin-lastname=User --admin-email=user@nike.com --admin-user=administrator --admin-password=admin123 --backend-frontname=admin --language=en_US --currency=USD --timezone=America/Los_Angeles --use-rewrites=1 --search-engine=elasticsearch7 --elasticsearch-host=localhost --elasticsearch-port=9200"
                sudo su magento -c "php bin/magento setup:upgrade --no-interaction; php bin/magento weltpixel:cleanup; php bin/magento weltpixel:less:generate"
                sudo su magento -c "php bin/magento setup:di:compile --no-interaction"
                sudo su magento -c "php bin/magento c:c"
                sudo su magento -c "find var generated vendor pub/static pub/media app/etc -type f -exec chmod g+w {} +;"
                sudo su magento -c "find var generated vendor pub/static pub/media app/etc -type d -exec chmod g+ws {} +;"
                