# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

resources:
  repositories:
  - repository: self
    type: git
    ref: main

stages:
- stage: test
  jobs:
  - deployment: Test
    displayName: Test
    environment:
      name: magento_local
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            displayName: "test lines"
            inputs:
              script: >-
                echo "No line"
                echo "Is needed"
   