trigger: none
resources:
  repositories:
  - repository: self
    type: git
    ref: main

parameters:
- name: branch
  displayName: Magento-base branch
  type: string
  default: jp/dev

name: 1.0$(rev:.r)

stages:
- stage: Build
  jobs:
  - job: Testing
    displayName: Test the checks
    workspace:
      clean: all
    steps:
    - task: Bash@3
      displayName: Just a step
      inputs:
        targetType: 'inline'
        script: |
          echo "Just a step"

- stage: DeployEnv
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - deployment: DeployEnv
    displayName: Deploy code
    environment:
      name: magento_local
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            displayName: "Pull repo"
            inputs:
              script: |
                cd /var/www/repo
                sudo git checkout $branch && sudo git pull
          - task: CmdLine@2
            displayName: "Create folder"
            inputs:
              script: |
                sudo rm -rf /var/www/repo/pub/media
                sudo cp -r /var/www/repo /var/www/releases/$(Build.BuildNumber)
                sudo ln -s -f /var/www/media /var/www/releases/$(Build.BuildNumber)/pub/
                sudo ln -s -f /var/www/env.php /var/www/releases/$(Build.BuildNumber)/app/etc/
                sudo chown -R magento:www-data /var/www/releases/$(Build.BuildNumber)
          - task: CmdLine@2
            displayName: "Build static"
            inputs:
              script: |
                cd /var/www/releases/$(Build.BuildNumber)
                sudo su magento -c "composer install --no-interaction"
                sudo su magento -c "php bin/magento setup:di:compile --no-interaction"
                sudo su magento -c "php bin/magento s:st:d -s compact -f --jobs=2"
                sudo su magento -c "php bin/magento weltpixel:less:generate"
                sudo su magento -c "php bin/magento weltpixel:css:generate --store=all"
                sudo chown -R magento:www-data .
                sudo su magento -c "find var generated vendor pub/static pub/media app/etc -type f -exec chmod g+w {} +;"
                sudo su magento -c "find var generated vendor pub/static pub/media app/etc -type d -exec chmod g+ws {} +;"
          - task: CmdLine@2
            displayName: "Upgrade"
            inputs:
              script: |
                cd /var/www/releases/$(Build.BuildNumber)
                function magento_maintenance_mode {
                local mode=$1
                sudo su magento -c "php bin/magento \"maintenance:${mode}\""
                }
                magento_maintenance_mode enable
                sudo su magento -c "php bin/magento setup:upgrade --keep-generated --no-interaction"
                sudo su magento -c "php bin/magento c:f"
                sudo su magento -c "php bin/magento in:rein"
                sudo rm /var/www/html
                sudo ln -f -s /var/www/releases/$(Build.BuildNumber) /var/www/html
                sudo chown -R magento:www-data /var/www/html
                sudo su magento -c "find var generated vendor pub/static pub/media app/etc -type f -exec chmod g+w {} +;"
                sudo su magento -c "find var generated vendor pub/static pub/media app/etc -type d -exec chmod g+ws {} +;"
                magento_maintenance_mode disable
          - task: CmdLine@2
            displayName: "Cleanup"
            inputs:
              script: |
                cd /var/www/releases/
                keep_releases=1
                releases=$(ls -tr -d */)
                RELEASES=($releases)
                redundant_number=$(( ${#RELEASES[@]} - $keep_releases))
                if (( $redundant_number > 0 )); then
                  for ((i = 0 ; i < redundant_number ; i++)); do
                      sudo rm -rf "${RELEASES[$i]}"
                  done
                fi