variables:
  isTestA: $[eq(variables['Build.SourceBranch'], 'refs/heads/test')]

trigger:
  branches:
    include:
    - main

resources:
  repositories:
  - repository: self
    type: git
    ref: main

name: 1.0$(rev:.r)
parameters:
  - name: branch
    type: string
    default: a11y
    

stages:
- stage: Build
  condition: eq(variables.isTestA, 'true')
  jobs:
  - job: Testing
    displayName: Test the checks
    workspace:
      clean: all
    steps:
    - checkout: self
      clean: true
    - task: Bash@3
      displayName: docker login        
      inputs:
        targetType: 'inline'
        script: |            
          echo "Testing checks for $(Build.SourceBranch)"

- stage: DeployEnv
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - deployment: DeployEnv
    displayName: Deploy code
    environment:
      name: magento_local
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            displayName: "Pull repo"
            inputs:
              script: |
                cd /home/vagrant/jp/magento-base
                if [[ "${{ parameters.branch }}" == "a11y" ]]; then git checkout jp/dev-accessibility; cd packages/magento2-jp; git checkout dev/magento-2.4.2-compatibility; fi
                if [[ "${{ parameters.branch }}" == "jp" ]]; then git checkout jp/dev; cd packages/magento2-jp; git checkout dev/magento-2.4.2-compatibility; fi
                git reset --hard
                git pull
          - task: CmdLine@2
            displayName: "Create folder"
            inputs:
              script: |
                sudo mkdir /var/www/${{ parameters.branch }}-$(Build.BuildNumber)
                sudo cp -r /home/vagrant/jp/magento-base/* /var/www/${{ parameters.branch }}-$(Build.BuildNumber)/
                sudo ln -s -f /var/www/media /var/www/${{ parameters.branch }}-$(Build.BuildNumber)/pub/
                sudo ln -s -f /var/www/shared/${{ parameters.branch }}/env.php /var/www/${{ parameters.branch }}-$(Build.BuildNumber)/app/etc/
                sudo chown -R magento:www-data /var/www/${{ parameters.branch }}-$(Build.BuildNumber)
          - task: CmdLine@2
            displayName: "Build static"
            inputs:
              script: |
                cd /var/www/${{ parameters.branch }}-$(Build.BuildNumber)
                sudo su magento -c "composer install --no-interaction"
                sudo su magento -c "php bin/magento setup:di:compile --no-interaction"
                sudo su magento -c "php bin/magento s:st:d en_US ja_JP -s compact -f"
                sudo chown -R magento:www-data .
                sudo su magento -c "find var generated vendor pub/static pub/media app/etc -type f -exec chmod g+w {} +;"
                sudo su magento -c "find var generated vendor pub/static pub/media app/etc -type d -exec chmod g+ws {} +;"
          - task: CmdLine@2
            displayName: "Upgrade"
            inputs:
              script: |
                #sudo su magento -c "php bin/magento setup:install --base-url=http://${{ parameters.branch }}.172.30.1.10.nip.io/ --db-host=localhost:3306 --db-name=${{ parameters.branch }} --db-user=root --db-password=P@ssw0rd --admin-firstname=Magento --admin-lastname=User --admin-email=user@nike.com --admin-user=administrator --admin-password=admin123 --backend-frontname=admin --language=en_US --currency=USD --timezone=America/Los_Angeles --use-rewrites=1 --search-engine=elasticsearch7 --elasticsearch-host=localhost --elasticsearch-port=9200"
                sudo su magento -c "php bin/magento setup:upgrade --no-interaction; php bin/magento weltpixel:cleanup; php bin/magento weltpixel:less:generate"
                sudo su magento -c "php bin/magento c:c"