trigger:
  branches:
    include:
    - jp/main

resources:
  repositories:
  - repository: self
    type: git
    ref: jp/main

stages:
- stage: Build
  jobs:
  - job: Testing
    displayName: Test the checks
    pool:
      name: Win
    workspace:
      clean: all
    steps:
    - checkout: self
      clean: true
    - task: PowerShell@2
      displayName: Test task
      inputs:
        targetType: 'inline'
        script: |
          echo "Testing envvar value: Build.SourceBranchName=$(Build.SourceBranchName)"
          echo "Testing envvar value: Build.SourceBranch=$(Build.SourceBranch)"