trigger:
  branches:
    include:
    - jp/main

resources:
  repositories:
  - repository: self
    type: git
    ref: jp/main

stages:
- stage: Build
  condition: eq(variables.isTestA, 'true')
  jobs:
  - job: Testing
    displayName: Test the checks
    workspace:
      clean: all
    steps:
    - checkout: self
      clean: true
    - task: PowerShell@2
      displayName: Test task
      inputs:
        targetType: 'inline'
        script: |
          echo "Testing checks with branch $(Build.SourceBranchName)"